language: java
jdk: oraclejdk8
sudo: false
install: false
before_install:
 - chmod +x mvnw
cache:
  directories:
    - $HOME/.m2/repository
after_success:
  - mvn clean -Pcoveralls cobertura:cobertura coveralls:report