language: java
jdk: oraclejdk8
sudo: false
install: false
cache:
  directories:
    - $HOME/.m2/repository
after_success:
  - mvn clean -U -T 1C -Pcoveralls -pl druid-spring-boot-starter -am cobertura:cobertura coveralls:report