language: java
jdk:
  - oraclejdk8
sudo: false
install: false
cache:
  directories:
    - $HOME/.m2/repository
after_success:
  - cd druid-spring-boot2-example/druid-spring-boot2-mybatis-example
  - mvn clean test -Pcoveralls jacoco:report coveralls:report