language: java
jdk:
  - oraclejdk8
sudo: false
install: false
cache:
  directories:
    - $HOME/.m2/repository
after_success:
  - cd druid-spring-boot-example && mvn clean -Pcoveralls cobertura:cobertura coveralls:report