debug: false

logging:
  level:
    root: info
    org.springframework: info
    org.springframework.jdbc: debug
    org.mybatis: debug
    com.github.trang: debug

spring:
  profiles:
    # 默认环境为 default，多数据源演示请改为 dynamic
    active: default
  output:
    ansi:
      enabled: detect
  datasource:
    url: jdbc:h2:file:./samples
    username: root
    password: 123456
    schema: classpath:/import.sql
    druid:
      # spring.datasource.druid 前缀的配置将注入到 DruidDataSource2Support，作为公共参数
      initial-size: 1
      min-idle: 1
      max-active: 10
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 1800000
      max-evictable-idle-time-millis: 25200000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      use-global-data-source-stat: true
      # 默认开启，当前已开启
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
      # 默认关闭，需手动开启，当前已开启
      slf4j:
        enabled: true
        connection-log-enabled: false
        statement-sql-format-option:
          upp-case: true
          pretty-format: false
        statement-executable-sql-log-enable: true
        result-set-log-enabled: false
      # 默认关闭，需手动开启，当前已开启
      wall:
        enabled: true
        log-violation: true
        throw-exception: false
        config:
          delete-where-none-check: true
      # 默认关闭，需手动开启，当前已关闭
      config:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      web-stat:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      aop-stat:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      stat-view-servlet:
        enabled: false
  transaction:
    rollback-on-commit-failure: true
  aop:
    auto: true
    proxy-target-class: true
  http:
    encoding:
      force: true
    converters:
      preferred-json-mapper: jackson

mybatis:
  type-aliases-package: com.github.trang.druid.example.model

---

debug: true

spring:
  profiles: default

---

debug: true

spring:
  profiles: dynamic
  autoconfigure:
    exclude:
      # 多数据源场景会导致 `javax.sql.DataSource` 和 `org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer`
      # 循环依赖，所以需要手动排除 `org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration`
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    druid:
      # 继承 spring.datasource.druid 前缀的配置，同时可以自定义配置，若名称相同则覆盖父配置
      data-sources:
        master:
          max-active: 50
          max-open-prepared-statements: 50
        slave:
          max-active: 25
          max-open-prepared-statements: 25

---

spring:
  profiles: config
  datasource:
    url: jdbc:h2:file:./samples
    username: root
    password: Biyu5YzU+6sxDRbmWEa3B2uUcImzDo0BuXjTlL505+/pTb+/0Oqd3ou1R6J8+9Fy3CYrM18nBDqf6wAaPgUGOg==
    schema: classpath:/import.sql
    druid:
      config:
        enabled: true

---

spring:
  profiles: features
  datasource:
    url: jdbc:h2:file:./samples
    username: root
    password: Biyu5YzU+6sxDRbmWEa3B2uUcImzDo0BuXjTlL505+/pTb+/0Oqd3ou1R6J8+9Fy3CYrM18nBDqf6wAaPgUGOg==
    schema: classpath:/import.sql
    druid:
      # 默认开启，当前已开启
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
      # 默认关闭，需手动开启，当前已开启
      slf4j:
        enabled: true
        connection-log-enabled: false
        statement-sql-format-option:
          upp-case: true
          pretty-format: false
        statement-executable-sql-log-enable: true
        result-set-log-enabled: false
      # 默认关闭，需手动开启，当前已开启
      wall:
        enabled: true
        log-violation: true
        throw-exception: false
        config:
          delete-where-none-check: true
      # 默认关闭，需手动开启，当前已开启
      config:
        enabled: true
      # 默认关闭，需手动开启，当前已开启
      web-stat:
        enabled: true
      # 默认关闭，需手动开启，当前已开启
      aop-stat:
        enabled: true
        patterns:
          - com.github.trang.*
      # 默认关闭，需手动开启，当前已开启
      stat-view-servlet:
        enabled: true
        reset-enable: true
---

debug: false

spring:
  profiles: actuator

management:
  security:
    enabled: false

endpoints:
  actuator:
    enabled: true
  druid:
    enabled: true